### ISSUE TITLE
IDEA 2020.2 Beta 中出现异常

### ISSUE THREAD

**Issue by cn-src** [huoguangjin/MultiHighlight#13]
IDEA 2020.2 Beta 中出现异常，这个应该是设置。但高亮效果也不工作。
```
cannot create configurable component

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'project' of com/intellij/codeInsight/daemon/impl/TrafficLightRenderer.<init> must not be null
	at com.intellij.codeInsight.daemon.impl.TrafficLightRenderer.$$$reportNull$$$0(TrafficLightRenderer.java)
	at com.intellij.codeInsight.daemon.impl.TrafficLightRenderer.<init>(TrafficLightRenderer.java)
	at com.intellij.codeInsight.daemon.impl.TrafficLightRenderer.<init>(TrafficLightRenderer.java:85)
	at top.rammer.multihighlight.ui.ColorPreviewPanel$1.<init>(ColorPreviewPanel.java:52)
	at top.rammer.multihighlight.ui.ColorPreviewPanel.<init>(ColorPreviewPanel.java:52)
	at top.rammer.multihighlight.ui.MultiHighlightConfigPanel.createPanel(MultiHighlightConfigPanel.java:59)
	at top.rammer.multihighlight.ui.MultiHighlightConfigPanel.createComponent(MultiHighlightConfigPanel.java:189)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createComponent(ConfigurableWrapper.java:172)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.lambda$createConfigurableComponent$4(ConfigurableCardPanel.java:115)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.createConfigurableComponent(ConfigurableCardPanel.java:111)
	at com.intellij.openapi.options.ex.ConfigurableCardPanel.create(ConfigurableCardPanel.java:59)
```

**Comment by n374** [comment]
类似的问题
在IDEA Ultimate 2020.2中，插件不工作，已禁用Downloaded下的所有插件。

**Comment by rishikeshmpawar** [comment]
facing the same issue with IntelliJ 2020.2...

**Comment by huoguangjin** [comment]
ok, I will check it out these days
it is time to fix and update..
I am sorry

抱歉 本职日常工作太忙 太久没更新插件了
最近相对闲下来了一点 下班后我会抽时间尽快修的

**Comment by huoguangjin** [comment]
fine, fatal bugs fixed today.
it will be published ASAP!

**Comment by huoguangjin** [comment]
:smiley: updated on branch [2.0.0-beta@dev](https://github.com/huoguangjin/MultiHighlight/tree/2.0.0-beta)
 
new version plugin is uploaded to marketplace and under review, it may be approved after two days
[releases/tag/2.0.0-beta](https://github.com/huoguangjin/MultiHighlight/releases/tag/2.0.0-beta) here is the pre-release distribution, follow the guide to download and install from disk if you like
 
:ok_hand: please leave comments if you have any issues

@cn-src @n374 @rishikeshmpawar

**Comment by rishikeshmpawar** [comment]
@huoguangjin I updated the plugin from MarketPlace and now it is working. Thanks!
