### ISSUE TITLE
IDE fatal errors on 2020.3

### ISSUE THREAD

**Issue by bedge** [huoguangjin/MultiHighlight#19]
Seems to work once on each IDE restart, then after that I start seeing these:

```
java.lang.NoSuchMethodError: 'com.intellij.openapi.util.Couple com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getUsages(com.intellij.psi.PsiFile, com.intellij.model.Symbol)'
	at top.rammer.multihighlight.highlight.MultiHighlightHandler.findSymbols(MultiHighlightHandler.java:109)
	at top.rammer.multihighlight.highlight.MultiHighlightHandler.lambda$invoke$0(MultiHighlightHandler.java:82)
	at com.intellij.openapi.project.DumbService.withAlternativeResolveEnabled(DumbService.java:337)
	at top.rammer.multihighlight.highlight.MultiHighlightHandler.invoke(MultiHighlightHandler.java:81)
	at top.rammer.multihighlight.action.MultiHighlightAction.lambda$actionPerformed$0(MultiHighlightAction.java:40)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at top.rammer.multihighlight.action.MultiHighlightAction.actionPerformed(MultiHighlightAction.java:38)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:281)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:615)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:675)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:674)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:522)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:892)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:837)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:507)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

```
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on November 30, 2020
Licensed to Roche ltd / Bruce Edge
Subscription is active until November 20, 2021
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Jenkins Plugin 0.13.10-2020.3
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, MultiHighlight, PlantUML integration, Quick Notes, awesome.console, color.scheme.GapStyle, com.alayouni.ansiHighlight, com.clutcher.comments_highlighter, com.crunch42.openapi, com.intellij.ideolog, com.mallowigi, com.markskelton.one-dark-theme, io.github.qeesung.component.HighlightBracketPair, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.intellij.plugins.hcl, org.zalando.intellij.swagger, tech.central.ai.awstail, DBN, zielu.gittoolbox, GrepConsole, Jenkins Control Plugin, String Manipulation, io.thundra.debugger, wide-task-browser, MavenRunHelper, com.chrisrm.idea.MaterialThemeUI, izhangzhihao.rainbow.brackets, pro.bashsupport, Pythonid, aws.toolkit, ru.adelf.idea.dotenv, org.asciidoctor.intellij.asciidoc


```

**Comment by huoguangjin** [comment]
to be fixed this weekend :ok_hand:

**Comment by huoguangjin** [comment]
OK, fixed!
New release is under approval
Please check [here releases v2.1.0](https://github.com/huoguangjin/MultiHighlight/releases/tag/v2.1.0) on IDE 2020.3
@bedge

**Comment by bedge** [comment]
Confirmed fixed. Thanks!
