### ISSUE TITLE
IDEA 2024.1 Exception Info

### ISSUE THREAD

**Issue by JohnWickzzz** [huoguangjin/MultiHighlight#42]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.huoguangjin.multihighlight.action.MultiHighlightAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: MultiHighlight]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

After upgrade IDEA to 2024.1, use the plugin to highlight words, it works, but will throw that exception message.

**Comment by khelifaadm** [comment]
same issue After upgrade IDEA to 2024.1

**Comment by huoguangjin** [comment]
It is just a warning for 2024.1, and it will not cause any problems.
I will fix it in a few days.
